{{- if not .Values.appCredentialsSecretName }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: adhoc-worker-credentials
  labels:
    {{- include "queryEngine.labels" . | nindent 4 }}
data:
  jrs.server.password: amFzcGVyYWRtaW4=
  jrs.proxy.password: amFzcGVyYWRtaW4=
  jndi.datasource.foodmart.password: {{ default "cG9zdGdyZXM=" .Values.foodmart.password }}
  jndi.datasource.sugarcrm.password: {{ default "cG9zdGdyZXM=" .Values.sugarcrm.password }}
  jndi.datasource.jasperserverAudit.password: {{ default "cG9zdGdyZXM=" .Values.audit.password }}

{{- end}}