apiVersion: v1
kind: Secret
metadata:
  name: {{ include "queryEngine.fullname" . }}
  labels:
    {{- include "queryEngine.labels" . | nindent 4 }}
type: Opaque
data:
  {{ (.Files.Glob "secrets/keystore/.jrsks").AsSecrets | indent 2 }}
  {{ (.Files.Glob "secrets/keystore/.jrsksp").AsSecrets | indent 2 }}