apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "queryEngine.labels" . | nindent 4 }}
  name: {{ include "queryEngine.fullname" . }}
  annotations:
    haproxy.org/check: "true"
    haproxy.org/forwarded-for: "true"
    haproxy.org/load-balance: "roundrobin"
    # haproxy.org/path-rewrite: /query-engine/(.*) /\1
    haproxy.org/pod-maxconn: "100"
spec:
  selector:
  {{- include "queryEngine.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8080

    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https