apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretLicenseName }}
  labels:
    helm.sh/chart: {{ include "jrs.chart" . }}
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/version: {{ .Values.jrsVersion }}

type: Opaque
data:
  {{ (.Files.Glob "secrets/license/jasperserver.license").AsSecrets | indent 2 }}
