{{- if and .Values.jms.enabled  (not .Values.jms.jmsBrokerUrl) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jms.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    helm.sh/chart: {{ include "jrs.chart" . }}
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/version: {{ .Values.jrsVersion }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jms.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jms.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.jms.name }}
          image: {{.Values.jms.imageName}}:{{ .Values.jms.imageTag}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort:  8161
              name: http
              protocol: TCP
            - containerPort: 61616
              name: tcp
              protocol: TCP

  {{ include "jmshealthcheck" .  | nindent 10 }}
  {{ include "jmsresources" .  | nindent 10 }}
  {{ include "jmssecuritycontext" . | nindent 10 }}

  {{- end -}}