apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretKeyStoreName }}
  labels:
    helm.sh/chart: {{ include "jrs.chart" . }}
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/version: {{ .Values.jrsVersion }}
  {{- include "jrs.selectorLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  {{ (.Files.Glob "secrets/keystore/.jrsks").AsSecrets | indent 2 }}
  {{ (.Files.Glob "secrets/keystore/.jrsksp").AsSecrets | indent 2 }}