{{- if .Values.rbac.create }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jrs.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets","configmap", "namespaces", "downwardAPI"]
    resourceNames: ["*"]
    verbs: ["get"]

{{- end }}