{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "queryEngine.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets" ,"configmaps", "namespaces", "downwardAPI"]
    resourceNames: [worker-properties, {{ include "queryEngine.fullname" . }} ,{{ include "queryEngine.fullname" . }}-additional, {{ default "adhoc-worker-credentials" .Values.appCredentialsSecretName }} ]
    verbs: ["get" ,"list", "watch"]

{{- end }}